name: build
on:
  push:
    branches:
      - master
      - main
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install cwltool
      - run: cwltool --validate app-package.cwl#s2-composites

  container-crop:
   
    needs: validate
    
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: wget https://github.com/mikefarah/yq/releases/download/${VERSION}/${BINARY} -O /usr/bin/yq 
        env:
          VERSION: v4.2.0
          BINARY: yq_linux_amd64
      - run: chmod +x /usr/bin/yq
      - run: echo "APP_VERSION=$( yq e '."s:softwareVersion"' app-package.cwl | tr -d "\n" )" >> $GITHUB_ENV
      - run: echo $APP_VERSION
      - run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin
      - run: |
        IMAGE_ID=docker.pkg.github.com/${{ github.repository }}/crop
        docker build src --file src/crop/Dockerfile --tag crop
        docker tag crop $IMAGE_ID:$APP_VERSION
        docker tag crop $IMAGE_ID:latest
        docker push $IMAGE_ID:$APP_VERSION
        docker push $IMAGE_ID:latest